name: Deploy Datasette service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_push_image:
    name: Build subject-set-search image
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'+%A %W %Y %X')"
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          ghcr.io/zooniverse/subject-set-search-api:latest
          ghcr.io/zooniverse/subject-set-search-api:${{ github.sha }}
        build-args: |
          BUILD_DATE: ${{ steps.date.outputs.date }}
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set the target AKS cluster
      uses: Azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_AKS }}
        cluster-name: microservices
        resource-group: kubernetes

    - name: Modify & apply template
      run: |
        kubectl apply -f kubernetes/deployment-production.yaml
        kubectl rollout restart deployment subject-set-search-api-production-app
  slack_notification:
    name: Slack notification
    uses: zooniverse/ci-cd/.github/workflows/slack_notification.yaml@main
    needs: [build_and_push_image, deploy]
    if: always()
    with:
      commit_id: ${{ github.sha }}
      job_name: Build subject-set-search image
      status: ${{ needs.build_and_push_image.result }}
      title: "Subject set search API deploy complete"
      title_link: "https://subject-set-search-api.zooniverse.org/subjects"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
